# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c70c5c9031f7b11e6413e439fb914486d97416e143aa175537f25ea6594e8ef59f74f66d4dbeabb3b1c7e09e43b32eb8b35047c18a42761e3c7c8629b7d3e8bd

test:
  secret_key_base: 5011a8924e8101b009888588670058fa4cd15a2003a9dd0b01d275d0da953e54b519035b74fb1e44d66c8fe6e1b4073fc74da09fe63a68f765367a8f2069216f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
